# Generated by Django 5.0.3 on 2024-03-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="public",
            new_name="make_public",
        ),
        migrations.AddField(
            model_name="article",
            name="publish_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.TextField(
                blank=True, help_text="Use commas to separate tags", null=True
            ),
        ),
    ]
